spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

logging.level.root=WARN
logging.level.com.example.agrokushproject=INFO

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
