spring.datasource.url=jdbc:postgresql://localhost:5432/agro_kush
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.SQL=DEBUG

cors.allowed-origins=http://localhost:3000
